# TAREA 04 
# CAMILA TORRES
# 12 DE SEPTIEMBRE DE 2024

## ACTIVIDAD 5

#### EJERCICIO 1

#### Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 9 gramos de proteína y  7 gramos de grasa. Así mismo, no se debe tener más de 2.5 gramos de fibra y 0.5 gramos de sal.

$$ \min_{p, m, c, a, t, g}  0.012p + 0.009m + 0.010c + 0.003a + 0.005t + 0.002g$$
$$ \text{s.t.} $$
$$ p + m + c + a + t + g = 100 $$
$$ -0.10p - 0.20m - 0.15c - 0.04t \leq -9 $$
$$ -0.08p - 0.10m - 0.11c - 0.01a - 0.01t \leq -7 $$
$$ 0.001p + .005m + 0.005c + 0.10a + 0.15t \leq 2.5 $$
$$ 0.002p + 0.005m + 0.007c + 0.002a + 0.008t \leq 0.5 $$

In [22]:
import numpy as np
c = np.array([
    0.012, 
    0.009, 
    0.010, 
    0.003,
    0.005,
    0.002
])
# A va a tener tantos renglones como restricciones y b tendrá tantas columnas como variables
Aub = np.array([
    [  1.000,  1.000, 1.000,  1.000,  1.000, 1],
    [ -0.100, -0.200,-0.150,  0.000, -0.040, 0],
    [ -0.080, -0.100,-0.110, -0.010, -0.010, 0],
    [  0.001,  0.005, 0.005,  0.100,  0.150, 0],
    [  0.002,  0.005, 0.007,  0.002,  0.008, 0]
])

bub = np.array([
     100, 
      -9,
      -7,
     2.5,
     0.5,
]) 

import scipy.optimize as opt
sol = opt.linprog(c, Aub, bub)
sol
# sol.x es solo el resultado en x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 0.63
              x: [ 0.000e+00  7.000e+01  0.000e+00  0.000e+00  0.000e+00
                   0.000e+00]
            nit: 1
          lower:  residual: [ 0.000e+00  7.000e+01  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
                 marginals: [ 4.800e-03  0.000e+00  1.000e-04  2.100e-03
                              4.100e-03  2.000e-03]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 3.000e+01  5.000e+00  0.000e+00  2.150e+00
                              1.500e-01]
                 marginals: [-0.000e+00 -0.000e+00 -9.000e

#### EJERCICIO 2

#### La Comisión Federal de Electricidad (CFE) dispone de tres plantas de generación para satisfacer la demanda diaria eléctrica en tres ciudades, Guadalajara, León y Morelia. Las plantas 1, 2 y 3 pueden satisfacer 75, 50 y 60 millones de kW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de 60, 45 y 60 millones de Kw al día respectivamente. Los costos asociados al envío de suministro energético por cada millón de kW entre cada planta y cada ciudad son los registrados en la siguiente tabla.a.

$$ \min_{$p_1g, p_1l, p_1m, p_2g, p_2l, p_2m, p_3g, p_3l, p_3m$}  5p_1g + 2p_1l + 7p_1m + 3p_2g + 4p_2l + 5p_2m + 5p_3g + 2p_3l + 3p_3m$$
$$ \text{s.t.} $$
$$ p_1g + p_1m + p_1l \leq 75 $$
$$ p_2g + p_2m + p_2l \leq 50 $$
$$ p_3g + p_3m + p_3l \leq 60 $$

$$ -p_1g + -p_2g + -p_3g \leq -60 $$
$$ -p_1l + -p_2l + -p_3l \leq -45 $$
$$ -p_1m + -p_2m + -p_3m \leq -60 $$

In [10]:
import numpy as np
c = np.array([
    5, 
    2, 
    7, 
    3,
    4,
    5,
    5,
    2,
    3
])
# A va a tener tantos renglones como restricciones y b tendrá tantas columnas como variables
Aub = np.array([
    [ 1,  1,  1,  0,  0,  0,  0,  0,  0],
    [ 0,  0,  0,  1,  1,  1,  0,  0,  0],
    [ 0,  0,  0,  0,  0,  0,  1,  1,  1],
    [-1,  0,  0, -1,  0,  0, -1,  0,  0],
    [ 0, -1,  0,  0, -1,  0,  0, -1,  0],
    [ 0,  0, -1,  0,  0, -1,  0,  0, -1]
])

bub = np.array([
     75, 
     50,
     60,
    -60,
    -45,
    -60
]) 

import scipy.optimize as opt
sol = opt.linprog(c, Aub, bub)
sol
# sol.x es solo el resultado en x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 470.0
              x: [ 1.000e+01  4.500e+01  0.000e+00  5.000e+01  0.000e+00
                   0.000e+00  0.000e+00  0.000e+00  6.000e+01]
            nit: 4
          lower:  residual: [ 1.000e+01  4.500e+01  0.000e+00  5.000e+01
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              6.000e+01]
                 marginals: [ 0.000e+00  0.000e+00  4.000e+00  0.000e+00
                              4.000e+00  4.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.0

---

## ACTIVIDAD 6

### Ejercicio 1.

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la tabla. Las mesas se venden en 9000, las sillas en 3000, los libreros en 10000, y las bases de cama en 9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera, ¿qué les conviene construir durante una semana para maximizar su ganancia?

- ¿Cuántas horas trabaja cada quién?
- ¿Cuánto material se usa?
- ¿Cuál es el ingreso total si se vende todo lo fabricado?

$$ \min_{as, am, al, ab, es, em, el, eb}  3000as + 3000es + 9000am + 9000em + 10000al + 10000el + 9000ab + 9000eb $$
$$ \text{s.t.} $$
$$ 1.5as + 4.5am + 6al + 4.5ab \leq 40 $$
$$ 1es + 3em + 4el + 3eb \leq 40 $$
$$ 2.4as + 2es + 7.2am + 6em + 6al + 5el + 6ab + 5eb \leq 100 $$

In [41]:
import numpy as np
c = np.array([
    -3000,
    -3000,
    -9000,
    -9000,
    -10000,
    -10000,
    -9000,
    -9000
])
Aub = np.array([
    [1.5, 0.0, 4.5, 0.0, 6.0, 0.0, 4.5, 0.0],
    [0.0, 1.0, 0.0, 3.0, 0.0, 4.0, 0.0, 3.0],
    [2.4, 2.0, 7.2, 6.0, 6.0, 5.0, 6.0, 5.0]
])

bub = np.array([
    40, 
    40,
    100
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

-178666.66666666663

In [43]:
solucion.x

array([0.        , 0.        , 0.        , 0.        , 6.66666667,
       4.        , 0.        , 8.        ])

In [45]:
Aub@solucion.x

array([ 40.,  40., 100.])

---

## 02 PROGRAMACIÓN LINEAL

### 2.1. Ejemplo básico
Una multinacional farmacéutica desea fabricar un compuesto nutritivo a base de dos productos A y B.  El producto A contiene  $30\%$ de proteínas,  un $1\%$ de grasas y un  $10\%$ de azúcares.  El producto B  contiene  un  $5\%$  de proteínas,  un  $7\%$ de grasas  y un  $10\%$  de  azúcares.

El compuesto debe de tener,  al menos, $25g$ de proteínas,  $6g$ de grasas y $30g$ de azúcares.  El coste del producto A es de $0.6$ u.m./g  y el de B es de $0.2$  u.m./g

Se desea encontrar la cantidad en gramos de cada producto para que el coste total sea mínimo.

Formular el problema de decidir cuánto hacer de cada producto como un problema de programación lineal.

$$ \min_{Xa, Xb}  0.6Xa + 0.2Xb $$
$$ \text{s.t.} $$
$$ -0.30Xa - 0.05Xb \leq -25 $$
$$ -0.01Xa - 0.07Xb \leq -6 $$
$$ -0.10Xa - 0.10Xb \leq -30 $$

In [39]:
import numpy as np
c = np.array([
    0.6,
    0.2
])
Aub = np.array([
    [-0.30, -0.05],
    [-0.01, -0.07],
    [-0.10, -0.10]
])

bub = np.array([
    -25, 
     -6, 
    -30
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

76.0

In [47]:
solucion.x

array([0.        , 0.        , 0.        , 0.        , 6.66666667,
       4.        , 0.        , 8.        ])

In [49]:
Aub@solucion.x

array([ 40.,  40., 100.])

### 2.2. Ejemplo básico 2
Una  fábrica  de  carrocerías  de  automóviles  y camiones  tiene  dos naves. 

+ En  la nave A,  para  hacer  la  carrocería  de  un  camión,  se  invierten  siete  días-operario,  para  fabricar  la  de  un  coche  se  precisan dos días-operario.

+ En la nave B se invierten tres días operario tanto en carrocerías de camión como de coche. 

Por limitaciones de mano de obra y maquinaria, la nave A dispone de $300$ días operario, y la nave B de $270$ días-operario.

Si los beneficios que se obtienen por cada camión son de $600$ u.m y por  cada  automóvil  $200$ u.m,  ¿cuántas  unidades  de  cada  uno  se deben  producir  para maximizar las  ganancias? 

**Nota:** el problema $\max_{\boldsymbol{x}}\boldsymbol{g}(\boldsymbol{x})$ es equivalente a $\min_{\boldsymbol{x}}-\boldsymbol{g}(\boldsymbol{x})$.

$$ \min_{Aa, Ac, Ba, Bc}  -200Aa - 600Ac - 200Ba - 600Bc $$
$$ \text{s.t.} $$
$$ 2Aa + 7Ac \leq 300 $$
$$ 3Ba + 3Bc \leq 270 $$

In [61]:
import numpy as np
c = np.array([
    -200,
    -600,
    -200,
    -600
])
Aub = np.array([
    [2, 7, 0, 0],
    [0, 0, 3, 3]
])

bub = np.array([
    300,
    270
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

-84000.0

In [63]:
solucion.x

array([150.,   0.,   0.,  90.])

In [65]:
Aub@solucion.x

array([300., 270.])

### **Actividad.** 

Mónica hace aretes y cadenitas de joyería. Es tan buena, que todo lo que hace lo vende.

Le toma 30 minutos hacer un par de aretes y una hora hacer una cadenita, y como Mónica también es estudihambre, solo dispone de 10 horas a la semana para hacer las joyas. Por otra parte, el material que compra solo le alcanza para hacer 15 unidades (el par de aretes cuenta como unidad) de joyas por semana.

La utilidad que le deja la venta de las joyas es $\$15$ en cada par de aretes y $\$20$ en cada cadenita.

¿Cuántos pares de aretes y cuántas cadenitas debería hacer Mónica para maximizar su utilidad?

Formular el problema en la forma explicada y obtener la solución gráfica (puede ser a mano).

**Diez minutos: quien primero lo haga, comparte pantalla para explicarlo y le subiré la nota de alguna tarea a 100.**

$$ \min_{A, C}  -15A - 20C $$
$$ \text{s.t.} $$
$$ 0.5A + 1C \leq 10 $$
$$ A + C \leq 15 $$

In [70]:
import numpy as np
c = np.array([
    -15,
    -20
])
Aub = np.array([
    [0.5, 1.0],
    [1.0, 1.0]
])

bub = np.array([
    10,
    15
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

-250.0

In [72]:
solucion.x

array([10.,  5.])

In [74]:
Aub@solucion.x

array([10., 15.])

### 4. Problema de transporte 1

Una  empresa tiene dos fábricas A y B.  En ellas  se fabrica un determinado  producto, a razón de 500  y 400 unidades por día respectivamente.  El producto  ha  de  ser distribuido posteriormente  a  tres  centros  C,  D  y  E,  que  requieren,  respectivamente,  200,  300  y  400  unidades.  Los  costos  de  transportar cada unidad del producto desde cada fábrica a cada centro distribuidor son los  indicados  en la tabla  siguiente: 

Factoría|C|D|E|Fabricación (Unidades)
:----|----|----|----|----
A|  50 u.m|60 u.m|10 u.m|500 u
B|  25 u.m|40 u.m|20 u.m|400 u
Demanda|200|300|400|

**¿De qué manera  deben  organizar  el transporte a fin de que los gastos sean mínimos?**


Resolver con `linprog`

$$ \min_{Ac, Ad, Ae, Bc, Bd, Be}  50Ac + 60Ad + 10Ae + 25Bc + 40Bd + 20Be $$
$$ \text{s.t.} $$
$$ -Ac - Bc \leq -200 $$
$$ -Ad - Bd \leq -300 $$
$$ -Ae - Be \leq -400 $$
$$ Ac + Ad + Ae \leq 500 $$
$$ Bc + Bd + Be \leq 400 $$

In [80]:
import numpy as np
c = np.array([
    50, 
    60,
    10, 
    25,
    40,
    20
])
Aub = np.array([
    [-1,  0,  0, -1,  0,  0],
    [ 0, -1,  0,  0, -1,  0],
    [ 0,  0, -1,  0,  0, -1],
    [ 1,  1,  1,  0,  0,  0],
    [ 0,  0,  0,  1,  1,  1]
])

bub = np.array([
    -200, 
    -300,
    -400, 
     500,
     400
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

23000.0

In [82]:
solucion.x

array([  0., 100., 400., 200., 200.,   0.])

In [84]:
Aub@solucion.x

array([-200., -300., -400.,  500.,  400.])

### 5. Optimización de inversión en bonos

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

$$ \min_{A1, A2, A3, A4, A5, A6}  -0.0865A1 - 0.095A2 - 0.1A3 - 0.0875A4 - 0.0925A5 - 0.09A6 $$
$$ \text{s.t.} $$
$$ A1 + A2 + A3 + A4 + A5 + A6 \leq 750000 $$
$$ -A1 - A2 - A4 - A6 \leq -375000 $$
$$ A1 \leq 187500 $$
$$ A2 \leq 187500 $$
$$ A3 \leq 187500 $$
$$ A4 \leq 187500 $$
$$ A5 \leq 187500 $$
$$ A6 \leq 187500 $$
$$ A2 + A3 + A5 \leq 262500 $$

In [87]:
import numpy as np
c = np.array([
    -0.0865,
    -0.095,
    -0.10,
    -0.0875,
    -0.0925,
    -0.090
])
Aub = np.array([
    [ 1,  1,  1,  1,  1,  1],
    [-1, -1,  0, -1,  0, -1],
    [ 1,  0,  0,  0,  0,  0],
    [ 0,  1,  0,  0,  0,  0],
    [ 0,  0,  1,  0,  0,  0],
    [ 0,  0,  0,  1,  0,  0],
    [ 0,  0,  0,  0,  1,  0],
    [ 0,  0,  0,  0,  0,  1],
    [ 0,  1,  1,  0,  1,  0],
])

bub = np.array([
     750000,
    -375000,
     187500, 
     187500,
     187500,
     187500,
     187500,
     187500,
     262500
])

import scipy.optimize as opt
solucion = opt.linprog(c, Aub, bub)
solucion.fun

-68887.5

In [89]:
solucion.x

array([112500.,  75000., 187500., 187500.,      0., 187500.])

In [91]:
Aub@solucion.x

array([ 750000., -562500.,  112500.,   75000.,  187500.,  187500.,
             0.,  187500.,  262500.])

---